- name: install mosquitto and client tools
  become: True
  apt:
    name: ['mosquitto', 'mosquitto-clients']
    cache_valid_time: "{{ cache_update_valid_secs }}"

- name: add MQTT listener
  become: True
  template:
    dest: /etc/mosquitto/conf.d/port.conf
    src: 04_mqtt_port.conf
    force: yes

- name: restart mosquitto
  become: True
  service:
    name: mosquitto
    state: restarted 

