# >COMPATIBILITY: this is all likely to change including kernel version

- name: Remove dependencies that are no longer required
  become: True
  apt:
    autoremove: yes

# install Python3 pip 
- name: install pip3
  become: True
  apt:
    name: python3-pip
    cache_valid_time: "{{ cache_update_valid_secs }}"

- name: install dependencies for adafruit script and ansible pids
  become: True
  pip:
    name:
      - adafruit-python-shell
      - click
      - psutil

- name: use running fbcp as proof pitft already installed
  community.general.pids:
    name: fbcp
  register: pid_of_fbcp

- name: remove temporary directory
  become: yes 
  when: not pid_of_fbcp.pids
  file: path={{ adafruit_tmp_dir }} state=absent
  ignore_errors: true

- name: create temporary  directory
  become: yes 
  when: not pid_of_fbcp.pids
  file: path={{ adafruit_tmp_dir }} state=directory

- name: clone adafruit repo
  become: True
  when: not pid_of_fbcp.pids
  git:
    repo: https://github.com/adafruit/Raspberry-Pi-Installer-Scripts.git
    dest: "{{ adafruit_tmp_dir }}"
    version: "{{ adafruit_git_version }}"

- name: run pitft script and REBOOT
  become: True
  when: not pid_of_fbcp.pids
  reboot:
    reboot_timeout: 120
    reboot_command: /usr/bin/python3 "{{ adafruit_tmp_dir }}/adafruit-pitft.py"  --display=28c --rotation=180 --install-type=fbcp --reboot=yes 

- name: remove temporary directory
  become: yes
  when: not pid_of_fbcp.pids
  file: path={{ adafruit_tmp_dir }} state=absent
  ignore_errors: true

- name: dpkg-reconfigure console-setup for better console fonts
  become: True
  debconf:
    name: console-setup
    question: "{{ item.question }}"
    value: "{{ item.value }}"
    vtype: select
  with_items:
    - { question: 'console-setup/fontface47', value: 'Terminus' }
    - { question: 'console-setup/fontsize-fb47', value: '6x12 (framebuffer only)' }
    - { question: 'console-setup/charmap47', value: 'UTF-8' }
    - { question: 'console-setup/codeset47', value: 'Guess optimal character set' }
