- name: set device_id
  tags: ble
  set_fact:
    device_id: "{{ ansible_eth0.macaddress | regex_replace(':', '') }}"

- name: set LAMPI hostname
  tags: ble
  become: True
  hostname:
    name: "LAMPI-{{ device_id }}"
  register: lampihostname

- name: reboot if hostname changed
  tags: ble
  become: True
  reboot:
    reboot_timeout: 180
  when: lampihostname.changed

- name: install supervisor bluetooth config
  become: True
  tags: ble
  template:
    dest: "/etc/supervisor/conf.d/{{ item.filename }}"
    owner: root
    mode: u+rw,g=r,o=r
    src: "{{ item.src }}"
  with_items:
    - { filename: "hci0_up.conf", src: "hci0_up.conf" } 
    - { filename: "bluetooth_service.conf", src: "bluetooth_service.conf" } 

- name: make supervisord aware of our new programs to manage
  become: True
  tags: ble
  supervisorctl:
    name: "{{ item }}"
    state: "present"
  with_items:
    - hci0_up
    - bluetooth_service
  
- name: install MQTT bridge configuration (updated)
  become: True
  tags: ble
  template:
    src: 09_mqtt_bridge.conf
    dest: /etc/mosquitto/conf.d/lampi_bridge.conf

- name: restart mosquitto
  become: True
  tags: ble
  service:
    name: mosquitto
    state: restarted 
